### PR TITLE
[MM-34601] Change "Invite Members" label to "Assign Commander"

### PR DESCRIPTION
**Pull request by JoelRummel**
#### Summary

This PR changes the Assign Commander selector dropdown to use the label "Assign Commander" instead of "Invite Members".

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/17349
JIRA ticket: https://mattermost.atlassian.net/browse/MM-34601

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Comment by lieut-data** [comment]
Thanks, @JoelRummel!

**Comment by lieut-data** [comment]
(I believe the failed tests are spurious here, and being investigated separately.)

**Comment by JoelRummel** [comment]
I figured as much - Cypress tests failed for me when I ran them locally on master.

**Review by agarciamontoro — APPROVED** [review]
Thank you, @JoelRummel! As Jesse said, the failing CI tests are because of an unrelated change.

**Comment by agarciamontoro** [comment]
Skipping QA review, as this changes only the copy of the menu. Let's wait for the CI fixes in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/516 to make CI happy and then we'll merge this on!

**Pull request merged**
