### PR TITLE
MM-36264 Restrict to E10 and remove from behind experimantal feature flag. 

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Restricts retrospective feature behind E10 and removes the experimental feature flag gate. 

Build on https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/610 for the generic upgrade component. 

#### Retrospective restrict screen
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36264

#### Checklist
~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
~~- [ ] Unit tests updated~~

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Sweet! 

Approving so I don't block.

But, we do need telemetry. See what I added here: https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/610/commits/4f3283b84a7f04970ac85b2af9660ca6585351d4

**Review by abhijit-singh — APPROVED** [review]
Looks good! Assuming the flows will be identical to the playbook dashboard.

@crspeller Can you do a quick check to make sure the colours don't get messed up in the dark themes? Thanks!

**Comment by crspeller** [comment]
@abhijit-singh Good call on checking the other themes. In all the shuffle I did forget to theme the SVG. However There seems to be a generic problem with all the SVGs. It might have something to do with the fade effect? 

image
image
image

**Comment by crspeller** [comment]
@abhijit-singh Figured it out. Fixed all of them:

image
image
image

**Review by agarciamontoro — APPROVED** [review]
Looks perfect! Thank you, @crspeller :)

**Pull request merged**
