### PR TITLE
MM-34718: fix incident welcome when filtering

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
When the incident list loads, check for incidents without filtering to reliably decide when to show the welcome screen.

(`master` is failing spuriously right now, but the specific test in question passes locally for me.)

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-34718

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Looks good!

Only thing I noticed while re-reading this code is that this screen will not update real-time, if someone else creates an incident. But that already happened before this PR, so nothing else to do here.

Thanks!

**Review by crspeller — APPROVED** [review]

**Review by prapti — APPROVED** [review]
The initial bug is fixed: the links in stats page open the incident list view with correct filters even when there aren't any incidents matching that filter.
Thanks Jesse!

**Pull request merged**
