### PR TITLE
MM-32852 - Fix for Mobile app: `/incident list`

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- List all non-archived incidents
- No tests because it's a quick fix on a function that isn't tested (not testable with the e2e tests, unless we set a "pretend not mobile" flag)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-32852

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
😃

**Review by agarciamontoro — APPROVED** [review]
Nice, thank you! :tada:

**Review by prapti — CHANGES_REQUESTED** [review]
@cpoile The list is showing up in the mobile app again :yay: The webapp however does not show the resolved incidents either, only 'Ongoing' ones. Could this be updated to only show the reported and active ones?
Thank you!

**Comment by cpoile** [comment]
@prapti Done, thanks!

**Comment by crspeller** [comment]
@prapti @cpoile I thought the RHS list only showed "Ongoing" incidents before? Which maps to "Reported" and "Active", not "Reported", "Active", and "Resolved.

**Comment by cpoile** [comment]
@crspeller I asked in the channel, @itao clarified that it should show all non-Archived incidents

**Review by prapti — APPROVED** [review]
Works as clarified as Tao. Approving.

**Pull request merged**
