### PR TITLE
Update mattermost-plugin-api to use the DB RPC API

### PR DESCRIPTION
**Pull request by agnivade**
We use the new NewClient constructor to let the DB RPC API work.
No further changes are needed.

### CODE REVIEW

**Comment by agnivade** [comment]
@lieut-data / @crspeller - One thing to consider would be that the new changes aren't backward compatible with older versions of MM. How do we handle situations like these?

**Review by lieut-data — APPROVED** [review]
I've pinged @itao, but given we're focussing on the versions shipping pre-packaged, I don't /think/ this will be a problem. Can you help bump `min_server_version` in our `plugin.json` @agnivade to make this dependency explicit?

**Comment by agnivade** [comment]
Done. :+1:

**Comment by agnivade** [comment]
The Cypress tests are failing with:

```
Failed: failed to upload plugin bundle: : Unable to restart plugin on upgrade., 

Usage:
    pluginctl deploy <plugin id> <bundle path>
    pluginctl disable <plugin id>
    pluginctl enable <plugin id>
    pluginctl reset <plugin id>
make: *** [Makefile:126: deploy] Error 1
```
Is that due to the bump of `min_server_version` or just flaky? I cannot see any more detailed logs.

**Comment by lieut-data** [comment]
I /think/ that's because the server is still `CurrentSchemaVersion = Version5360`. I'm not sure how that version is being bumped anymore -- I would have expected it to have been bumped by now. @cpanato / @metanerd, do you know when the `master` and `cloud` branches will have their versions formally bumped?

**Comment by cpanato** [comment]
humm, i dont have this answer, maybe @amyblais

**Comment by amyblais** [comment]
Carlos / Elisabeth normally bump the version when the self-managed release branch is cut. It can probably done earlier as needed.

**Comment by agnivade** [comment]
Maybe I'll just revert the min version bump and get the commit in, and when 5.37 is released, bump the version up. There isn't a big deal either way from what I am surmising.

**Comment by metanerd** [comment]
We should own this. I will add a job to bump `model/version.go` in the master branch after the latest stable release got released.

**Pull request merged**
