### PR TITLE
Support prompting for feedback

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
If the NPS plugin is running, show a "Give Feedback" button in the backstage, redirecting to the @surveybot DM and "faking" a prompt from that bot for feedback:

image

image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36566

#### Checklist
- ~~[] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [ ] Unit tests updated

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Cool!

I'm a little concerned we're going back to classnames (vs styled-components), but this looks like less code and cleaner that a styled-components version.

**Comment by lieut-data** [comment]
> I'm a little concerned we're going back to classnames (vs styled-components), but this looks like less code and cleaner that a styled-components version.

Yeah, that's just me ~~being lazy~~ trying to keep the PR as small as possible. I briefly contemplated fixing the existing cases I was copying, but figured we should probably just do a full sweep here instead.

**Review by calebroseland — APPROVED** [review]
LGTM!

**Pull request merged**
