### PR TITLE
MM-33335  Use CurrentStatus as source of truth. 

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Since we are unable to distinguish between the cases of a brand new incident and a migrated incident with no status updates, the method of using status updates as the source of truth for current status is not viable. So to support the migration case I have simplified and now use the CurrentStatus field in the incident as the source of truth. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33335

### CODE REVIEW

**Review by prapti — APPROVED** [review]
Plugin upgrade now changes all previously ongoing incidents' status to "Active" regardless of whether the status was updated or not. Looks good to me!
Approving this prior to dev reviews since it needs to go in 1.5. However, if there is any change request in this PR, please reassign me for a second review and I'll be happy to do it. Otherwise let's merge it 🙂

**Review by cpoile — APPROVED** [review]
This feels better anyway. I didn't really like that way of computing status, a little too error-prone.

**Review by lieut-data — APPROVED** [review]
Nice -- glad we were writing the field already, simplifying this migration!

**Comment by lieut-data** [comment]
@crspeller, leaving you to merge and handle any release branches necessary.

**Pull request merged**
