### PR TITLE
MM-32128 New Status Badges

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
- Modifies the status badges to have colour codes. 
- Adds the actual status rather than "Ongoing" or "Ended"
- Replaces text status with a badge in the RHS list and the RHS incident summary. 

#### RHS Summary
image

####  Backstage Incident List
image

####  RHS Incident List
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32128

### CODE REVIEW

**Review by itao — APPROVED** [review]
🌈  LGTM

**Review by cpoile — APPROVED** [review]

**Review by agarciamontoro — APPROVED** [review]
Looking good!

Only non blocking comment: we need to replace `Verify the title shows "Ongoing"` with `Verify the title shows "Reported"` in the incident_rhs_list_spec comments.

**Review by prapti — COMMENTED** [review]
@crspeller The functionality mostly works great. Here are a couple things I noticed:
1. The "Archived" badge renders without consistent border in light and dark theme in all three browsers in the RHS, however renders fine in the backstage
Screen Shot 2021-02-24 at 11 02 11 AM
Screen Shot 2021-02-24 at 10 57 43 AM

2. The text in the badges, compared to other dark themes, are difficult to read in Monokai theme that at least one of our customers use/used (?)
Screen Shot 2021-02-24 at 11 04 50 AM

Would you want take a look into these in this PR?

**Comment by crspeller** [comment]
@prapti 

1. Pushed a fix for the border. 
2. Looks fine in all the default themes. Might be a bug in the theme? Let's open up a separate ticket for UX to have a look at, if that sounds good to you.

**Review by prapti — APPROVED** [review]
Thank you for the fix! Looks great now. Yeah, I'll file a different ticket for Monokai.

For reference, I've added the following tests to the test plan:
Tests for light and dark theme in all three browsers:

1. "Reported” status has yellow badge
2.  “Active” status has red badge
3.  “Resolved” status has green badge
4.  “Archived” status has white badge
5.  Status badge appears next to the Incident Title in Incident RHS
6.  Status badge changes appropriately in the RHS Summary view when incident status is updated
7.  Status badge changes appropriately in the RHS List view when incident status is updated
8.  Status badge changes appropriately in the Incident Backstage List view
9.  Status badge renders properly in light theme
10.  Status badge renders properly in dark theme

**Pull request merged**
