### PR TITLE
MM-31643 Add reporter field.

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Adds a reporter field to the incident sidebar. 

Ready for review after https://github.com/mattermost/mattermost-plugin-incident-management/pull/429 is merged.

#### Screenshot
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31643

### CODE REVIEW

**Review by cpoile — APPROVED** [review]

**Review by agarciamontoro — APPROVED** [review]
Cool, thanks! I left a couple of comments with typos, but approving beforehand.

**Comment by prapti** [comment]
Getting a "An internal error has occurred. Check app server logs for details" in local server. Will look more into it tomorrow.

**Comment by agarciamontoro** [comment]
@prapti, could it be that you're getting errors in the migrations from testing different PRs that change the database?

**Comment by prapti** [comment]
@agarciamontoro Maybe if the migration issue was when downgrading from 1.4.0 to 1.3.1+... 
I tested this PR branch on local (fresh after `nuke`) and cloud servers where it was happening in all three servers. Just now I re-nuked my local and it's working normally, but it's still doing that on https://im-test.test.mattermost.cloud/. I think I'll spin up a fresh cloud server again and give it a try.

**Comment by crspeller** [comment]
@prapti The strangeness was probably due to our migrations and a conflict. I just pushed a merge from master to fix the conflict.

**Review by prapti — APPROVED** [review]
Yeah, working much better now :)
Reporter field works as expected. Tests will be added to the test plan.
Approving.

**Comment by crspeller** [comment]
@prapti Great! Sorry for the run around!

**Pull request merged**
