### PR TITLE
MM-30878 Change format of dates that are not this year

### PR DESCRIPTION
**Pull request by berkeka**
#### Summary

Changes incident create date format if year is different than the current year.

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/16399

### CODE REVIEW

**Review by crspeller — COMMENTED** [review]
Great! But I think we need to do the same for `endedAt` below.

**Comment by berkeka** [comment]
> Great! But I think we need to do the same for `endedAt` below.

@crspeller Do we still want show "--" for incidents that were created before 2020-01-01?

**Comment by crspeller** [comment]
@berkeka I think that's a backwards compatibility thing. So we should keep that.

**Review by crspeller — APPROVED** [review]
Looks good! Thanks for the contribution!

**Review by cpoile — APPROVED** [review]
Looks great, thanks @berkeka !

**Comment by prapti** [comment]
The only easy way to test this is using the the `/incident test` tool that @agarciamontoro developed I believe. The command however is not working as expected, and @agarciamontoro is looking into fixing a bug. Will check back again once there is a way to create incidents in the past dates.
Thank you for your patience!

**Comment by agarciamontoro** [comment]
Ready to test!

**Review by prapti — APPROVED** [review]
Thank you for your patience through the review process @berkeka! And thank you to @agarciamontoro for helping with the foundational work into place to make testing this set of changes possible!
Everything looks great. I ran some tests to ensure that the newly created incidents and the old data migration is normal.
Approving to merge for the v1.7 release 🎉

**Pull request merged**
