### PR TITLE
Upgrade to node 16 & npm 7

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- I recommend installing `nvm` and running `nvm install 16` and `nvm use 16`, that will get you to `node v16.4.0` and `npm v7.18.1`
- Our circleci `config.yml` is messy, I want to take some tech debt time and clean it up. I also want to put all the cypress setup into our new docker container. Until then, we're installing cypress manually. (like before) But we can do better.
- Oh: There's lots of cypress noise in the tests now. I'm pretty sure it's because we're installing cypress dependencies manually. This will be fixed when we add a cypress image to our base image.

#### Ticket Link
- n/a

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
Yay!

**Comment by lieut-data** [comment]
Looks good and installs cleanly! I did notice the following warning though:
> npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

Not sure if this was already there, but sharing in case we ever encounter a related issue.

**Review by lieut-data — APPROVED** [review]

**Comment by cpoile** [comment]
@lieut-data That looks like it's being pulled in by babel runtime and babel preset-env. I have to investigate how to get rid of it.

**Comment by cpoile** [comment]
@lieut-data Ah! `@babel/runtime-corejs2` is being pulled in by our old version of react-bootstrap! @hmhealey does that sound right?

**Comment by cpoile** [comment]
I'll merge this now, since we've been depending on `core-js 2` for a long time, and the fix won't be in this PR. Hopefully updating react-bootstrap will remove it.

**Pull request merged**
